const dataWayang = [
  {
    "Nama": "Nakula",
    "Asal": "India kuno",
    "Pembuat": "Sukarman",
    "Tanggal Dibuat": "1986/1989",
    "Medium": "Kulit kerbau, Cat air dicampur perekat",
    "Penjelasan": "Nakula adalah penunggang kuda dan pemanah yang ulung, jujur, setia, taat beragama, dan pandai menyimpan rahasia.",
    "Gambar": "image/wayang/Nakula.png",
  },
  {
    "Nama": "Singa Nila (Bali)",
    "Asal": "Bali",
    "Pembuat": "tidak dikenal",
    "Tanggal Dibuat": "tidak dikenal",
    "Medium": "Kulit kerbau, Cat air dicampur perekat",
    "Penjelasan": "Singa Nila (Bali) adalah representasi karakter hewan mitologis khas Bali yang perannya cenderung sebagai kekuatan alam atau gaib yang harus dihadapi tokoh protagonis.",
    "Gambar": "image/wayang/Singa_Nila.png",
  },
  {
    "Nama": "Raden Lesmono Widagdo (Surakarta)",
    "Asal": "Surakarta",
    "Pembuat": "Tidak dikenal",
    "Tanggal Dibuat": "tidak dikenal",
    "Medium": "Kulit kerbau, Cat air dicampur perekat",
    "Penjelasan": "Raden Lesmono Widagdo adalah representasi kesetiaan, keberanian, dan pengorbanan seorang adik kepada kakaknya dalam tradisi pewayangan Jawa, menjadikannya salah satu tokoh ksatria yang patut diteladani.",
    "Gambar": "image/wayang/Raden_Lesmono_Widagdo.png",
  },
  {
    "Nama": "Prabu Rahwana (Surakarta)",
    "Asal": "Surakarta",
    "Pembuat": "Sukarman",
    "Tanggal Dibuat": "1985",
    "Medium": "Kulit kerbau, Cat air dicampur perekat",
    "Penjelasan": "Prabu Rahwana adalah raja raksasa dari kerajaan Alengka dan tokoh antagonis utama dalam kisah Ramayana karena menculik Dewi Sinta, melambangkan angkara murka.",
    "Gambar": "image/wayang/Prabu_Rahwana_(Surakarta).png",
  },
  {
    "Nama": "Arjuna",
    "Asal": "India",
    "Pembuat": "Tidak Diketahui",
    "Tanggal Dibuat": "2009",
    "Medium": "Kulit kerbau, Cat air dicampur perekat",
    "Penjelasan": "Arjuna adalah ksatria anggota Pandawa, putra ketiga Prabu Pandu, yang dikenal sebagai pemanah ulung, berwajah tampan, berwatak halus dan bijaksana, serta bergelar Dananjaya atau Permadi.",
    "Gambar": "image/wayang/Arjuna.png",
  },
  {
    "Nama": "Raden Patah",
    "Asal": "Palembang",
    "Pembuat": "Suryadi Wano Surhardjo",
    "Tanggal Dibuat": "1975",
    "Medium": "Kulit kerbau, Cat air dicampur perekat",
    "Penjelasan": "Raden Patah adalah tokoh sejarah dan wayang yang dikenal sebagai pendiri dan Sultan pertama Kesultanan Demak, yang berjasa memodifikasi bentuk wayang kulit agar sesuai dengan ajaran Islam.",
    "Gambar": "image/wayang/Raden_Patah.png",
  },
  {
    "Nama": "Prabu Kresna (Cirebon)",
    "Asal": "Cirebon",
    "Pembuat": "Tidak Diketahui",
    "Tanggal Dibuat": "Tidak Diketahui",
    "Medium": "Kulit kerbau, Cat air dicampur perekat",
    "Penjelasan": "Prabu Kresna adalah Raja Dwarawati, titisan Dewa Wisnu, yang dikenal sebagai penasihat ulung Pandawa dan ahli strategi utama dalam Perang Bharatayudha.",
    "Gambar": "image/wayang/Prabu_Kresna_(Cirebon).png",
  },
  {
    "Nama": "Dursosono",
    "Asal": "Jawa",
    "Pembuat": "Tidak Diketahui",
    "Tanggal Dibuat": "Tidak Diketahui",
    "Medium": "Kulit kerbau, Cat air dicampur perekat",
    "Penjelasan": "Dursasana adalah adik Duryudana dari kelompok Kurawa yang terkenal karena kesombongan dan tindakan memalukannya saat berusaha menelanjangi Dewi Drupadi di depan umum, yang berakhir dengan kematiannya di tangan Bima.",
    "Gambar": "image/wayang/Dursosono.png",
  },
  {
    "Nama": "Raja TIiam",
    "Asal": "Sulawesi Selatan",
    "Pembuat": "Tidak Diketahui",
    "Tanggal Dibuat": "Tidak Diketahui",
    "Medium": "Kulit kerbau, Cat air dicampur perekat",
    "Penjelasan": "Tidak Diketahui.",
    "Gambar": "image/wayang/Raja_Tliam.png",
  },
  {
    "Nama": "Prabu Baladewa (Cirebon)",
    "Asal": "Cirebon",
    "Pembuat": "Tidak Diketahui",
    "Tanggal Dibuat": "Tidak Diketahui",
    "Medium": "Kulit kerbau, Cat air dicampur perekat",
    "Penjelasan": "Prabu Baladewa adalah Raja Mandura, kakak kandung Prabu Kresna yang berkulit putih, berwatak keras hati dan mudah marah tetapi jujur dan bijaksana, serta memiliki senjata sakti Gada Nanggala.",
    "Gambar": "image/wayang/Prabu_Baladewa (Cirebon).png",
  },
  {
    "Nama": "Romo Jangkah",
    "Asal": "Tidak Diketahui",
    "Pembuat": "Sukarman",
    "Tanggal Dibuat": "1985, 1989",
    "Medium": "Kulit kerbau, Cat air dicampur perekat",
    "Penjelasan": "Romo Jangkah adalah tokoh sentral dalam Ramayana dan merupakan putra Raja Dasarata.",
    "Gambar": "image/wayang/Romo_Jangkah.png",
  },
  {
    "Nama": "Pangeran Diponegoro",
    "Asal": "Jawa Tengah, Yogyakarta",
    "Pembuat": "Raden Mas Sayid",
    "Tanggal Dibuat": "1945/1950",
    "Medium": "Kulit kerbau, Cat air dicampur dengan perekat",
    "Penjelasan": "Pangeran Diponegoro adalah pahlawan nasional dari Kesultanan Yogyakarta yang memimpin Perang Jawa (1825–1830) melawan penjajah Belanda dan kini kisahnya diangkat dalam lakon Wayang Diponegoro yang mengacu pada Babad Diponegoro.",
    "Gambar": "image/wayang/Pangeran_Diponegoro.png",
  },
  {
    "Nama": "Bung Karno",
    "Asal": "Diterima sebagai hadiah dari Wereldmuseum Rotterdam",
    "Pembuat": "Raden Mas Sayid",
    "Tanggal Dibuat": "1945/1950",
    "Medium": "Kulit kerbau, Cat air dicampur perekat",
    "Penjelasan": "Bung Karno adalah Proklamator dan Presiden pertama RI yang sangat mengagumi budaya wayang, di mana namanya diambil dari tokoh pewayangan Karna, dan ia sering menggunakan filosofi kesatria Jawa dalam pidato serta kepemimpinannya.",
    "Gambar": "image/wayang/Bung_Karno.png"
  },
  {
    "Nama": "Gatot Kaca",
    "Asal": "Jawa Tengah",
    "Pembuat": "Wayan Winten",
    "Tanggal Dibuat": "Abad 19",
    "Medium": "Kulit kerbau, Cat air dicampur dengan perekat",
    "Penjelasan": "Gatotkaca adalah putra Bima dari Kerajaan Pringgadani yang dijuluki 'Otot Kawat Tulang Besi' karena kesaktiannya mampu terbang dan kebal senjata, yang ia peroleh setelah dicemplungkan ke Kawah Candradimuka.",
    "Gambar": "image/wayang/Gatot_Kaca.png",
  },
  {
    "Nama": "Patih Sangkuni",
    "Asal": "Gandara",
    "Pembuat": "Bambang Suwarno",
    "Tanggal Dibuat": "2014",
    "Medium": "Kulit kerbau, Cat air dicampur dengan perekat",
    "Penjelasan": "Patih Sangkuni adalah Patih Kerajaan Astina dan paman para Kurawa yang terkenal sangat licik, pandai menghasut, dan memutarbalikkan fakta, menjadikannya dalang utama di balik seluruh perselisihan hingga pecahnya Perang Bharatayudha.",
    "Gambar": "image/wayang/Patih_Sangkuni.png",
  },
  {
    "Nama": "Punto Dewo",
    "Asal": "Tidak Diketahui",
    "Pembuat": "Sukarman",
    "Tanggal Dibuat": "1986/1989",
    "Medium": "Kulit kerbau, Cat air dicampur dengan perekat",
    "Penjelasan": "Punto Dewo adalah raja raksasa dari Kerajaan Alengka yang memiliki satu mata di dahinya, saudara Prabu Rahwana, yang dikenal sangat perkasa dan akhirnya gugur di tangan Bima dalam Perang Baratayudha.",
    "Gambar": "image/wayang/Punto_Dewo.png",
  },
  {
    "Nama": "Semar Lurah",
    "Asal": "Jawa",
    "Pembuat": "Saderi",
    "Tanggal Dibuat": "2010",
    "Medium": "Kulit kerbau, Cat air dicampur perekat",
    "Penjelasan": "Semar adalah tokoh punakawan yang wujudnya lucu dan penuh paradoks, tetapi merupakan penjelmaan Batara Ismaya yang bertugas sebagai pengasuh, penasihat, dan guru spiritual bagi Pandawa.",
    "Gambar": "image/wayang/Semar_Lurah.png",
  },
  {
    "Nama": "Mohammad Hatta",
    "Asal": "Diterima sebagai hadiah dari Wereldmuseum Rotterdam",
    "Pembuat": "Raden Mas Sayid",
    "Tanggal Dibuat": "1945/1950",
    "Medium": "Kulit kerbau, Cat air dicampur perekat",
    "Penjelasan": "Mohammad Hatta adalah Proklamator Kemerdekaan RI dan Wakil Presiden pertama yang dikenal sebagai tokoh yang sangat jujur, disiplin, pro-rakyat, serta merupakan Bapak Koperasi Indonesia dan seorang intelektual yang sangat mencintai buku.",
    "Gambar": "image/wayang/Mohammad_Hatta.png",
  },
  {
    "Nama": "Raden Bakhtiar",
    "Asal": "Tidak Diketahui",
    "Pembuat": "Amak Rahimah",
    "Tanggal Dibuat": "1925",
    "Medium": "Kulit kerbau, Cat air dicampur perekat",
    "Penjelasan": "Tidak Diketahui.",
    "Gambar": "image/wayang/Raden_Bakhtiar.png",
  },
  {
    "Nama": "Hanuman",
    "Asal": "India",
    "Pembuat": "Sukarman",
    "Tanggal Dibuat": "1985/1989",
    "Medium": "Kulit kerbau, Cat air dicampur dengan perekat",
    "Penjelasan": "Hanuman adalah kera putih berwujud manusia, putra Batara Bayu, yang dikenal sangat setia dan berani sebagai senapati Prabu Rama dalam misi pencarian dan penyelamatan Dewi Sinta di Kerajaan Alengka.",
    "Gambar": "image/wayang/Hanuman.png",
  },
  {
    "Nama": "Bratasena",
    "Asal": "Tidak Diketahui",
    "Pembuat": "Niin Neran Ciracas",
    "Tanggal Dibuat": "Tidak Diketahui",
    "Medium": "Kulit kerbau, Cat air dicampur perekat",
    "Penjelasan": "Bratasena adalah nama masa muda dari Bima (Werkudara), Pandawa kedua, yang berwatak tegas, jujur, dan berani, yang kemudian dikenal sakti dan memiliki senjata Kuku Pancanaka.",
    "Gambar": "image/wayang/Bratasena.png",
  },
  {
    "Nama": "Bala dewa",
    "Asal": "Jawa Barat",
    "Pembuat": "Tidak Diketahui",
    "Tanggal Dibuat": "Tidak diketahui",
    "Medium": "Kulit kerbau, Cat air dicampur dengan perekat",
    "Penjelasan": "Prabu Baladewa (atau Kakrasana) adalah Raja Mandura, kakak kandung Prabu Kresna yang berkulit putih, berwatak keras hati dan mudah marah tetapi jujur dan bijaksana, serta memiliki pusaka sakti Gada Nanggala.",
    "Gambar": "image/wayang/Bala_Dewa.png",
  },
  {
    "Nama": "Anggada",
    "Asal": "India",
    "Pembuat": "Sukasman",
    "Tanggal Dibuat": "1964",
    "Medium": "Kulit kerbau, Cat air dicampur perekat",
    "Penjelasan": "Anggada (Hanggada) adalah wanara (kera) berbulu merah dan putra dari Resi Subali yang dikenal sangat tangkas dan setia, menjabat sebagai salah satu senapati utama dalam pasukan kera Prabu Rama melawan Rahwana.",
    "Gambar": "image/wayang/Anggada.png",
  },
  {
    "Nama": "Gondo Mono",
    "Asal": "Solo",
    "Pembuat": "Tidak dikenal",
    "Tanggal Dibuat": "Tidak Diketahui",
    "Medium": "Kulit kerbau, Cat air dicampur perekat",
    "Penjelasan": "Patih Gondomono (atau Arya Gandamana) adalah Patih Kerajaan Hastina pada masa Prabu Pandu, yang dikenal sangat sakti dan jujur, tetapi akhirnya difitnah oleh Suman (Sengkuni) hingga ia harus meninggalkan kedudukannya.",
    "Gambar": "image/wayang/Gondo_Mono.png",
  },
  {
    "Nama": "Raseksi",
    "Asal": "Tidak Diketahui",
    "Pembuat": "Tidak dikenal",
    "Tanggal Dibuat": "Tidak Dikehaui",
    "Medium": "Kulit Kerbau, Cat air dicampur dengan perekat",
    "Penjelasan": "Raseksi adalah sebutan umum dalam pewayangan untuk raksasa perempuan yang biasanya berwatak murka dan sering dimunculkan sebagai representasi dari tokoh dewi yang sedang terkena tulah atau kutukan.",
    "Gambar": "image/wayang/Raseksi.png",
  },
  {
    "Nama": "Duryudono",
    "Asal": "India Utara",
    "Pembuat": "Tidak Diketahui",
    "Tanggal Dibuat": "Tidak Diketahui",
    "Medium": "Kulit kerbau, Cat air dicampur perekat",
    "Penjelasan": "Duryudana adalah sulung dari seratus Kurawa dan Raja Astina yang menjadi tokoh antagonis utama dalam Mahabharata, dikenal karena sifatnya yang ambisius, mudah terhasut oleh Sengkuni, dan akhirnya gugur di tangan Bima.",
    "Gambar": "image/wayang/Duryudono.png",
  },
  {
    "Nama": "Janoko",
    "Asal": "Yogyakarta",
    "Pembuat": "Tidak dikenal",
    "Tanggal Dibuat": "Tidak Diketahui",
    "Medium": "Kulit Kerbau, Cat air dicampur dengan perekat",
    "Penjelasan": "Janaka adalah nama lain dari Arjuna, ksatria Pandawa ketiga yang terkenal sangat tampan, cerdik, sakti dalam memanah, ahli bertapa dan berguru, serta bergelar Dananjaya atau Permadi.",
    "Gambar": "image/wayang/Janoko.png",
  },
  {
    "Nama": "Panji Inukertapati",
    "Asal": "Jawa Timur",
    "Pembuat": "Tidak diketahui",
    "Tanggal Dibuat": "Tidak Diketahui",
    "Medium": "Kulit kerbau, Cat air dicampur dengan perekat",
    "Penjelasan": "Panji Inu Kertapati adalah putra mahkota Kerajaan Jenggala, tokoh utama roman klasik Jawa, dikenal sebagai ksatria tampan yang sering menyamar dalam pengembaraannya mencari cinta sejatinya, Galuh Candra Kirana.",
    "Gambar": "image/wayang/Panji_Inukertapati.png",
  },
  {
    "Nama": "Prabu Alam Dahur",
    "Asal": "Tidak Diketahui",
    "Pembuat": "Amak Rahimah",
    "Tanggal Dibuat": "1925",
    "Medium": "Kulit kerbau, Cat air dicampur perekat",
    "Penjelasan": "Tidak Diketahui.",
    "Gambar": "image/wayang/Prabu_Alam_Dahur.png",
  },
  {
    "Nama": "Tugu Waseso",
    "Asal": "Jawa",
    "Pembuat": "Tidak dikenal",
    "Tanggal Dibuat": "1934",
    "Medium": "Kulit kerbau, Cat air dicampur perekat",
    "Penjelasan": "Prabu Tuguwasesa adalah raja Kerajaan Gilingwesi yang memiliki kekuatan besar dan dikalahkan oleh Arjuna, sehingga ia menampakkan wujud aslinya sebagai Bima (Werkudara).",
    "Gambar": "image/wayang/Tugu_Waseso.png",
  },
  {
    "Nama": "Gatotkaca (Banyumas)",
    "Asal": "Banyumas",
    "Pembuat": "Tidak Dikenal",
    "Tanggal Dibuat": "Abad 19",
    "Medium": "Kulit kerbau, Cat air dicampur perekat",
    "Penjelasan": "Gatotkaca versi Banyumas memiliki ciri khas visual yang cenderung lebih sederhana dan realistis, tetapi tetap dikenal sebagai ksatria sakti putra Bima dengan julukan 'Otot Kawat Tulang Besi' yang mampu terbang dan menjadi Raja di Pringgadani.",
    "Gambar": "image/wayang/Gatotkaca_(Banyumas).png",
  },
  {
    "Nama": "Bagong",
    "Asal": "Jawa",
    "Pembuat": "Saderi",
    "Tanggal Dibuat": "2010",
    "Medium": "Kulit kerbau, Cat air dicampur perekat",
    "Penjelasan": "Bagong adalah anak bungsu dari Punakawan yang bertubuh tambun dan lugu, diciptakan dari bayangan Semar yang melambangkan rakyat jelata yang lugas, humoris, dan berani bersuara apa adanya.",
    "Gambar": "image/wayang/Bagong.png",
  },
  {
    "Nama": "Raden Haryo MIngdo",
    "Asal": "Tidak Diketahui",
    "Pembuat": "Pringgo, Mardi, Jarot",
    "Tanggal Dibuat": "1988/1992",
    "Medium": "Kulit kerbau, Cat air dicampur perekat",
    "Penjelasan": "Tidak Diketahui.",
    "Gambar": "image/wayang/Raden_Haryo_Mingdo.png",
  },
  {
    "Nama": "Bima (Banjar)",
    "Asal": "Banjar",
    "Pembuat": "Tidak Diketahui",
    "Tanggal Dibuat": "2009",
    "Medium": "Kulit kerbau, Cat air dicampur perekat",
    "Penjelasan": "Bima dalam pewayangan Banjar sama dengan versi Jawa (Pandawa kedua), yaitu ksatria gagah perkasa yang jujur dan setia, memiliki senjata Kuku Pancanaka, serta dikenal sakti dan berwatak keras namun berhati lembut.",
    "Gambar": "image/wayang/Bima_(Banjar).png",
  },
  {
    "Nama": "Lasmana Dikomara",
    "Asal": "Jawa",
    "Pembuat": "Tidak Diketahui",
    "Tanggal Dibuat": "Tidak Diketahui",
    "Medium": "Kulit kerbau, Car air dicampur perekat",
    "Penjelasan": "Lesmana Dikomara adalah putra mahkota Prabu Duryudana dari Astina yang digambarkan berwatak manja, sombong, pengecut, dan gugur di tangan Abimanyu dalam Perang Baratayudha.",
    "Gambar": "image/wayang/Lasmana_Dikomara.png",
  },
  {
    "Nama": "Bima Sena",
    "Asal": "Jawa",
    "Pembuat": "Sukarman",
    "Tanggal Dibuat": "2009",
    "Medium": "Kulit kerbau, Cat air dicampur perekat",
    "Penjelasan": "Bima Sena (Werkudara) adalah putra kedua dari lima Pandawa yang dikenal sebagai ksatria paling kuat, jujur, lugas, anti-basa-basi, bersenjatakan Kuku Pancanaka dan Gada Rujakpala, serta merupakan titisan dari Batara Bayu.",
    "Gambar": "image/wayang/Bima_Sena.png",
  },
  {
    "Nama": "Raden Werkudoro",
    "Asal": "Tidak Diketahui",
    "Pembuat": "Bambang Suwarno",
    "Tanggal Dibuat": "2014",
    "Medium": "Kulit kerbau, Cat air dicampur perekat",
    "Penjelasan": "Raden Werkudara adalah Pandawa kedua dan putra titisan Batara Bayu yang dikenal karena kekuatan fisik luar biasa, berwatak jujur, teguh, dan kasar kepada siapa pun kecuali Dewa Ruci, serta bersenjatakan Kuku Pancanaka dan Gada Rujakpala.",
    "Gambar": "image/wayang/Raden_Werkudoro.png",
  },
  {
    "Nama": "Raden Danur Wendo",
    "Asal": "Jawa",
    "Pembuat": "Tidak Diketahui",
    "Tanggal Dibuat": "Tidak Diketahui",
    "Medium": "Kulit kerbau, Cat air dicampur dengan perekat",
    "Penjelasan": "Tidak Diketahui.",
    "Gambar": "image/wayang/Raden_Danur_Wendo.png",
  },
  {
    "Nama": "Pratsongko",
    "Asal": "India",
    "Pembuat": "Tidak dikenal",
    "Tanggal Dibuat": "",
    "Medium": "Kulit kerbau, Cat air dicampur perekat",
    "Penjelasan": "Prabu Wratsangka (Sangka) adalah putra bungsu Prabu Matswapati dari Kerajaan Wirata yang diangkat menjadi panglima perang Pandawa, namun ia gugur di tangan Begawan Drona.",
    "Gambar": "image/wayang/Pratsongko.png",
  },
  {
    "Nama": "Prabu Rahwana",
    "Asal": "Palembang",
    "Pembuat": "Mbah Karmo",
    "Tanggal Dibuat": "Tidak diketahui",
    "Medium": "Kulit kerbau, Cat air dicampur perekat",
    "Penjelasan": "Prabu Rahwana (sering juga disebut Dasamuka) adalah raja raksasa berkepala sepuluh dari Kerajaan Alengka yang menjadi antagonis utama dalam wiracarita Ramayana karena perbuatannya menculik Dewi Sinta.",
    "Gambar": "image/wayang/Prabu_Rahwana.png",
  },
  {
    "Nama": "Onterja",
    "Asal": "Jawa",
    "Pembuat": "Tidak dikenal",
    "Tanggal Dibuat": "Tidak diketahui",
    "Medium": "Kulit Kerbau, Cat air dicampur perekat",
    "Penjelasan": "Onterja adalah putra sulung Bima dari Dewi Nagagini yang memiliki kesaktian luar biasa—termasuk kebal senjata dan kemampuan berjalan di dalam tanah—namun wafat secara tragis atas siasat Kresna sebelum Perang Baratayudha.",
    "Gambar": "image/wayang/Onterja.png",
  },
  {
    "Nama": "Gangge Mine",
    "Asal": "Tidak diketahui",
    "Pembuat": "Amak Rahimah",
    "Tanggal Dibuat": "Tidak Diketahui",
    "Medium": "Kulit kerbau, Cat air dicampur perekat",
    "Penjelasan": "Gangge Mine adalah bidadari dari kahyangan yang dikutuk turun ke bumi, menjadi istri Prabu Santanu dari Astina, dan kemudian dikenal sebagai ibu dari Resi Bisma.",
    "Gambar": "image/wayang/Gangge_Mine.png",
  },
  {
    "Nama": "Syeikh Wali Lanang",
    "Asal": "Tidak Diketahui",
    "Pembuat": "Suryadi Wanosuhardjo",
    "Tanggal Dibuat": "Tidak diketahui",
    "Medium": "Kulit kerbau, Cat air dicampur perekat",
    "Penjelasan": "Syeikh Wali Lanang adalah julukan lain dari Maulana Ishaq, seorang ulama penyebar Islam di Jawa Timur dan merupakan ayah dari Sunan Giri (salah satu Wali Songo).",
    "Gambar": "image/wayang/Syeikh_Wali_Lanang.png",
  },
  {
    "Nama": "Bisma",
    "Asal": "India",
    "Pembuat": "Tidak diketahui",
    "Tanggal Dibuat": "Tidak diketahui",
    "Medium": "Kulit kerbau, Cat air dicampur perekat",
    "Penjelasan": "Bisma (Dewabrata) adalah kakek yang sangat dihormati oleh Pandawa dan Kurawa, dikenal karena sumpah dahsyatnya untuk tidak menikah seumur hidup, dan gugur sebagai Mahasenapati Kurawa di Perang Baratayudha.",
    "Gambar": "image/wayang/Bisma.png",
  },
  {
    "Nama": "Prabu Brawijaya",
    "Asal": "Kerajaan Majapahit",
    "Pembuat": "Suryadi Wanosuhardjo",
    "Tanggal Dibuat": "1975",
    "Medium": "Kulit kerbau, Cat air dicampur perekat",
    "Penjelasan": "Prabu Brawijaya adalah gelar bagi beberapa raja di Majapahit, yang paling terkenal adalah Brawijaya V, raja terakhir Majapahit yang dikisahkan memiliki putra Raden Patah dan konon moksa di Gunung Lawu.",
    "Gambar": "image/wayang/Prabu_Brawijaya.png",
  },
  {
    "Nama": "Nala Gareng",
    "Asal": "Jawa",
    "Pembuat": "Saderi",
    "Tanggal Dibuat": "2010",
    "Medium": "Kulit kerbau, Cat air dicampur perekat",
    "Penjelasan": "Nala Gareng adalah putra sulung Semar dari kelompok Punakawan yang digambarkan memiliki cacat fisik sebagai simbol agar manusia selalu berhati-hati dalam bertindak dan tidak mengambil hak orang lain.",
    "Gambar": "image/wayang/Nala_Gareng.png",
  },
  {
    "Nama": "Hanoman",
    "Asal": "India",
    "Pembuat": "Tidak Diketahui",
    "Tanggal Dibuat": "Tidak Diketahui",
    "Medium": "Kulit kerbau, Cat air dicampur perekat",
    "Penjelasan": "Hanoman adalah kera putih berwujud manusia, putra Batara Bayu, yang dikenal sangat setia dan berani sebagai senapati Prabu Rama dalam misi pencarian dan penyelamatan Dewi Sinta di Kerajaan Alengka.",
    "Gambar": "image/wayang/Hanoman.png",
  },
  {
    "Nama": "Raden Sadewo (Surakarta)",
    "Asal": "Surakarta",
    "Pembuat": "Tidak dikenal",
    "Tanggal Dibuat": "Tidak Diketahui",
    "Medium": "Kulit kerbau, Cat air dicampur perekat",
    "Penjelasan": "Raden Sadewa adalah Pandawa termuda, saudara kembar Nakula, yang dikenal sangat bijaksana, cerdas (terutama dalam ilmu perbintangan), dan menjadi satu-satunya ksatria yang berhasil meruwat Batari Durga.",
    "Gambar": "image/wayang/Raden_Sadewo_(Surakarta).png",
  },
  {
    "Nama": "Sri Rama",
    "Asal": "India",
    "Pembuat": "Tidak dikenal",
    "Tanggal Dibuat": "Tidak Diketahui",
    "Medium": "Kulit kerbau, Cat air dicampur perekat",
    "Penjelasan": "Sri Rama Wijaya adalah putra mahkota Kerajaan Ayodya dan titisan Dewa Wisnu yang dikenal sebagai sosok Manusia Sempurna, yang hidupnya didedikasikan untuk menegakkan dharma dan menumpas angkara murka Rahwana demi menyelamatkan istrinya, Dewi Sinta.",
    "Gambar": "image/wayang/Sri_Rama.png",
  },
  {
    "Nama": "Dewi Sinta",
    "Asal": "Tidak diketahui",
    "Pembuat": "Sukarman",
    "Tanggal Dibuat": "1986/1990",
    "Medium": "Kulit kerbau, Cat air dicampur perekat",
    "Penjelasan": "Dewi Sinta adalah istri setia dari Sri Rama yang merupakan titisan Dewi Widowati dan menjadi simbol kemurnian, kesucian, serta keteguhan hati meskipun diculik dan menghadapi godaan dari Prabu Rahwana.",
    "Gambar": "image/wayang/Dewi_Sinta.png",
  },
  {
    "Nama": "Raden Gunungsari (Surakarta)",
    "Asal": "Surakarta",
    "Pembuat": "Tidak dikenal",
    "Tanggal Dibuat": "Tidak Diketahui",
    "Medium": "Kulit kerbau, Cat air dicampur perekat",
    "Penjelasan": "Raden Gunungsari adalah tokoh utama dalam Serat Panji dan adik laki-laki Dewi Sekartaji, digambarkan sebagai ksatria yang berwatak halus, rendah hati, dan bijaksana, sering berkelana, dan terkadang disamakan dengan karakter Arjuna atau Samba.",
    "Gambar": "image/wayang/Raden_Gunungsari_(Surakarta).png",
  },
  {
    "Nama": "Umbu Karna",
    "Asal": "Nusa Tenggara Timur",
    "Pembuat": "Mbah Karmo",
    "Tanggal Dibuat": "Tidak diketahui",
    "Medium": "Kulit kerbau, Cat air dicampur perekat",
    "Penjelasan": "Umbu Karna adalah adik kandung Prabu Rahwana yang berwujud raksasa besar, tetapi memiliki hati yang jujur dan nasionalisme tinggi yang membuatnya gugur sebagai pembela tanah air Alengka bukan karena membela Rahwana.",
    "Gambar": "image/wayang/Umbu_Karna.png",
  },
  {
    "Nama": "Prabu Sasra",
    "Asal": "Tidak diketahui",
    "Pembuat": "Sukarman",
    "Tanggal Dibuat": "Tidak diketahui",
    "Medium": "Kulit kerbau, Cat air dicampur dengan perekat",
    "Penjelasan": "Prabu Sasra kemungkinan merujuk pada Prabu Arjunasasrabahu, Raja Mahespati yang terkenal sakti mandraguna dan merupakan titisan Dewa Wisnu yang pernah mengalahkan dan mengikat Prabu Rahwana.",
    "Gambar": "image/wayang/Prabu_Sasra.png",
  },
  {
    "Nama": "Abimanyu",
    "Asal": "India",
    "Pembuat": "Tidak dikenal",
    "Tanggal Dibuat": "Tidak Diketahui",
    "Medium": "Kulit kerbau, Cat air dicampur perekat",
    "Penjelasan": "Abimanyu (Angkawijaya) adalah putra Arjuna dan Dewi Subadra yang berwatak lembut namun sangat pemberani dan jujur, yang wafat secara heroik dan tragis saat dikepung senapati Kurawa setelah berhasil memecahkan formasi Cakrabyuha dalam Perang Bharatayudha.",
    "Gambar": "image/wayang/Abimanyu.png",
  },
  {
    "Nama": "Jambalita Petruk",
    "Asal": "Jawa",
    "Pembuat": "Saderi",
    "Tanggal Dibuat": "2010",
    "Medium": "Kulit kerbau, Cat air dicampur perekat",
    "Penjelasan": "Petruk adalah salah satu Punakawan yang paling jenaka, cerdas, dan tinggi dengan ciri khas hidung panjang, dikenal dengan berbagai nama alias, meskipun Jamblahita lebih sering dikaitkan dengan Bagong versi Jawa Timuran.",
    "Gambar": "image/wayang/Jambalita_Petruk.png",
  },
  {
    "Nama": "Raden Sadewo",
    "Asal": "Jawa",
    "Pembuat": "Tidak dikenal",
    "Tanggal Dibuat": "Tidak diketahui",
    "Medium": "Kulit kerbau, Cat air dicampur perekat",
    "Penjelasan": "Raden Sadewa (Tangsen) adalah Pandawa bungsu dan kembaran Nakula yang dikenal karena kebijaksanaan luar biasa, keahlian dalam astronomi, dan kemampuannya untuk menyucikan Batari Durga.",
    "Gambar": "image/wayang/Raden_Sadewo.png",
  },
  {
    "Nama": "Broto Seno",
    "Asal": "Jawa Tengah",
    "Pembuat": "Sukasman",
    "Tanggal Dibuat": "1964",
    "Medium": "Kulit kerbau, Cat air dicampur perekat",
    "Penjelasan": "Brotoseno adalah nama muda dari Werkudara (Bima), Pandawa kedua yang berwatak tegas, lurus, dan setia pada kebenaran, serta memiliki kekuatan fisik luar biasa dengan senjata Kuku Pancanaka.",
    "Gambar": "image/wayang/Broto_Seno.png",
  },
  {
    "Nama": "Gandamana",
    "Asal": "Purwakarta",
    "Pembuat": "Tidak Diketahui",
    "Tanggal Dibuat": "2009",
    "Medium": "Kulit kerbau, Cat air dicampur perekat",
    "Penjelasan": "Gandamana (Arya Gandamana) adalah Patih Kerajaan Hastina di masa Prabu Pandu yang terkenal sangat sakti, jujur, dan berani membela kebenaran, tetapi ia dikalahkan oleh tipu muslihat Suman sehingga kehilangan jabatan patih.",
    "Gambar": "image/wayang/Gandamana.png",
  },
  {
    "Nama": "Raden Umbakarna",
    "Asal": "Tidak Diketahui",
    "Pembuat": "Tidak Diketahui",
    "Tanggal Dibuat": "Tidak Diketahui",
    "Medium": "Kulit kerbau, Cat air dicampur perekat",
    "Penjelasan": "Raden Umbakarna kemungkinan besar adalah variasi penyebutan dari Kumbakarna, adik kandung Prabu Rahwana yang berwujud raksasa besar dengan hati yang jujur dan patriotik, yang gugur membela tanah air Alengka.",
    "Gambar": "image/wayang/Raden_Umbakarna.png",
  },
  {
    "Nama": "Batara Narada",
    "Asal": "Jawa",
    "Pembuat": "Tidak dikenal",
    "Tanggal Dibuat": "1946",
    "Medium": "Kulit kerbau, Cat air dicampur perekat",
    "Penjelasan": "Batara Narada adalah Patih dan Penasihat utama Batara Guru di Kahyangan Suralaya, yang meskipun berwujud cebol, gendut, dan suka melawak, dikenal sebagai dewa yang paling bijaksana, ramah, dan jujur.",
    "Gambar": "image/wayang/Batara_Narada.png",
  },
  {
    "Nama": "Aswatama",
    "Asal": "India",
    "Pembuat": "Sukasman",
    "Tanggal Dibuat": "1964",
    "Medium": "Kulit kerbau, Cat air dicampur perekat",
    "Penjelasan": "Aswatama adalah putra tunggal Resi Drona yang sangat disayangi dan dikenal sebagai tokoh yang penuh dendam yang melakukan pembantaian anak-anak Pandawa di akhir Perang Bharatayudha.",
    "Gambar": "image/wayang/Aswatama.png",
  },
  {
    "Nama": "Raden Sari Wahono",
    "Asal": "Diterima oleh-oleh dari Miswan Iswanto, Sanggar Rumiyati, Jakarta.",
    "Pembuat": "Pringgo, Mardi, Jarot",
    "Tanggal Dibuat": "1992",
    "Medium": "Kulit Kerbau, Cat air dicampur perekat",
    "Penjelasan": "Tidak Diketahui.",
    "Gambar": "image/wayang/Raden_Sari_Wahono.png",
  },
  {
    "Nama": "Matswadati",
    "Asal": "India",
    "Pembuat": "Tidak dikenal",
    "Tanggal Dibuat": "Tidak Diketahui",
    "Medium": "Kulit kerbau, Cat air dicampur perekat",
    "Penjelasan": "Prabu Matswapati adalah Raja Negeri Wirata yang arif dan bijaksana, dikenal karena telah memberikan perlindungan dan tempat persembunyian kepada para Pandawa selama masa hukuman penyamaran mereka, dan menjadi pendukung setia Pandawa dalam Perang Bharatayudha.",
    "Gambar": "image/wayang/Matswadati.png",
  },
  {
    "Nama": "Jayakusuma",
    "Asal": "Jawa Barat",
    "Pembuat": "Tidak dikenal",
    "Tanggal Dibuat": "1992",
    "Medium": "Kulit kerbau, Cat air dicampur dengan perekat",
    "Penjelasan": "Jayakusuma adalah nama samaran yang digunakan oleh Raden Panji Inu Kertapati (tokoh utama Cerita Panji) selama pengembaraan dan penyamarannya, yang menunjukkan kecakapan dan kesaktiannya dalam menaklukkan kerajaan lain demi mencari tunangannya, Galuh Candra Kirana.",
    "Gambar": "image/wayang/Jayakusuma.png",
  },
  {
    "Nama": "Prabu Antarja",
    "Asal": "Jawa",
    "Pembuat": "Tidak dikenal",
    "Tanggal Dibuat": "Tidak dikenal",
    "Medium": "Kulit kerbau, Cat air dicampur perekat",
    "Penjelasan": "Prabu Antareja adalah putra sulung Bima dari Dewi Nagagini, yang berkulit kebal sisik ular, memiliki kesaktian berjalan di dalam tanah dan lidah beracun, dan merupakan ksatria Pandawa yang gugur sebelum Bharatayudha atas siasat Kresna.",
    "Gambar": "image/wayang/Prabu_Antarja.png",
  },
  {
    "Nama": "Raden Kumbakarna (Bali)",
    "Asal": "Bali",
    "Pembuat": "Tidak dikenal",
    "Tanggal Dibuat": "Tidak diketahui",
    "Medium": "Kulit kerbau, Cat air dicampur perekat",
    "Penjelasan": "Kumbakarna adalah adik Rahwana yang berwujud raksasa besar namun berhati ksatria dan jujur, yang gugur secara heroik di medan perang Ramayana, bukan karena membela kakaknya, melainkan demi membela tanah air Alengka dari kehancuran.",
    "Gambar": "image/wayang/Raden_Kumbakarna_(Bali).png",
  },
  {
    "Nama": "Trupada",
    "Asal": "Bali",
    "Pembuat": "Tidak dikenal",
    "Tanggal Dibuat": "TIdak Diketahui",
    "Medium": "Kulit kerbau, Cat air dicampur perekat",
    "Penjelasan": "Prabu Trupada adalah Raja Kerajaan Pancala dan mertua Pandawa, yang permusuhan lamanya dengan Resi Drona menjadi salah satu pemicu utama Perang Bharatayudha, di mana ia akhirnya gugur di tangan Drona.",
    "Gambar": "image/wayang/Trupada.png",
  },
  {
    "Nama": "Raden Arjuna",
    "Asal": "Yogyakarta",
    "Pembuat": "Keluarga Ngabean",
    "Tanggal Dibuat": "1917",
    "Medium": "Kulit kerbau, Cat air dicampur dengan perekat",
    "Penjelasan": "Raden Arjuna adalah Pandawa ketiga yang terkenal sebagai pemanah terhebat di dunia, berparas menawan, dan merupakan ksatria yang gigih bertapa untuk mencari ilmu dan senjata sakti.",
    "Gambar": "image/wayang/Raden_Arjuna.png",
  },
  {
    "Nama": "Prabu Karna (Palembang)",
    "Asal": "Sumatera Selatan",
    "Pembuat": "Mbah Karmo",
    "Tanggal Dibuat": "Tidak Diketahui",
    "Medium": "Kulit Hewan",
    "Penjelasan": "Prabu Karna adalah raja di Awangga dan kakak tiri para Pandawa yang sangat setia kepada Duryudana dan gugur sebagai Panglima Perang Kurawa dalam pertarungan melawan adiknya, Arjuna.",
    "Gambar": "image/wayang/Prabu_Karna_(Palembang).png",
  },
  {
    "Nama": "Pandu Dewanata",
    "Asal": "Tidak Diketahui",
    "Pembuat": "Sukasman",
    "Tanggal Dibuat": "1964",
    "Medium": "Kulit kerbau, Cat air dicampur perekat",
    "Penjelasan": "Prabu Pandu Dewanata adalah Raja Hastinapura, ayah dari kelima Pandawa yang berwajah tampan dan mahir memanah, namun wafat di usia muda akibat kutukan Resi Kindama.",
    "Gambar": "image/wayang/Pandu_Dewanata.png",
  },
  {
    "Nama": "Prabu Rahwana (Yogyakarta)",
    "Asal": "Yogyakarta",
    "Pembuat": "Tidak dikenal",
    "Tanggal Dibuat": "Tidak Diketahui",
    "Medium": "Kulit kerbau, Cat air dicampur perekat",
    "Penjelasan": "Prabu Rahwana versi Yogyakarta digambarkan sebagai raja raksasa dari Kerajaan Alengka yang berwatak angkara murka, serakah, dan tamak yang menjadi antagonis utama dalam Ramayana karena menculik Dewi Sinta.",
    "Gambar": "image/wayang/Prabu_Rahwana_(Yogyakarta).png",
  },
  {
    "Nama": "Menak Koncar",
    "Asal": "Jawa Timur",
    "Pembuat": "Tidak dikenal",
    "Tanggal Dibuat": "Abad 14",
    "Medium": "Kulit kerbau, Cat air dicampur dengan perekat",
    "Penjelasan": "Menak Koncar kemungkinan merujuk pada Minak Jingga atau tokoh dalam Wayang Menak, di mana tokoh-tokoh ini sering diangkat sebagai pahlawan lokal dalam cerita-cerita tentang penyebaran Islam atau masa kejayaan Majapahit.",
    "Gambar": "image/wayang/Menak_Koncar.png",
  },
  {
    "Nama": "Sadewo",
    "Asal": "India",
    "Pembuat": "Sukarman",
    "Tanggal Dibuat": "1986/1989",
    "Medium": "Kulit kerbau, Cat air dicampur perekat",
    "Penjelasan": "Sadewa adalah anggota termuda dari Pandawa Lima, putra Prabu Pandu dan Dewi Madrim yang dikenal sangat bijaksana, cerdas di bidang astronomi, ahli pengobatan, dan memiliki kesaktian untuk mengetahui kejadian yang akan datang.",
    "Gambar": "image/wayang/Sadewo.png",
  }
];
